import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import React, { useState } from 'react';
import Link from 'next/link'; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [count, setCount] = useState(0);

  const handleIncrement = () => {
    setCount(count + 1);
  };

  const handleDecrement = () => {
    setCount(Math.max(0, count - 1));
  };

  return (
    <>
      <Head>
        <title>Jonathan Alexis Rodriguez Salmeron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="https://nextjs.org/icons/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <div style={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
            <p style={{ fontSize: '2rem' }}>You clicked {count} times</p>
            <button style={{ fontSize: '2rem', padding: '1rem' }} onClick={handleDecrement}>-</button>
            <button style={{ fontSize: '2rem', padding: '1rem' }} onClick={handleIncrement}>+</button>
          </div>

          {}
          <div style={{ marginTop: '20px', textAlign: 'center' }}>
            <Link href="/page2">
              <button style={{ fontSize: '1rem', padding: '1rem' }}>Cambiar Página</button>
            </Link>
          </div>

          <div className={styles.ctas}>
            {}
          </div>
        </main>
        <footer className={styles.footer}>
          {}
        </footer>
      </div>
    </>
  );
}
